[[redirects]]
  from = "https://www.csgo-demo-manager.com"
  to = "https://cs-demo-manager.com"
  status = 301
  force = true

[[redirects]]
  from = "https://csgo-demo-manager.com"
  to = "https://cs-demo-manager.com"
  status = 301
  force = true

[[redirects]]
  from = "https://www.csgo-demos-manager.com"
  to = "https://cs-demo-manager.com"
  status = 301
  force = true

[[redirects]]
  from = "https://csgo-demos-manager.com"
  to = "https://cs-demo-manager.com"
  status = 301
  force = true

[[redirects]]
  from = "https://www.demo-manager.com"
  to = "https://cs-demo-manager.com"
  status = 301
  force = true

[[redirects]]
  from = "https://demo-manager.com"
  to = "https://cs-demo-manager.com"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "interest-cohort=()"